#ifndef DAFNYUTILS_IO_STARTUP_H
#define DAFNYUTILS_IO_STARTUP_H

#include <stdint.h>

/* Wire integers are explicitly encoded little-endian; these are not C structs. */
#define DFY_STARTUP_CONTROL_MAGIC "DFYSTRT2"
#define DFY_STARTUP_EVENT_MAGIC "DFYSTEV2"
#define DFY_STARTUP_EARLY_MAGIC "DFYSEAR2"
#define DFY_STARTUP_EARLY_BYTES 64u
#define DFY_STARTUP_VERSION 2u
#define DFY_STARTUP_CONTROL_BYTES 72u
#define DFY_STARTUP_EVENT_HEADER_BYTES 32u
#define DFY_STARTUP_SNAPSHOT_BYTES 1024u
#define DFY_STARTUP_STANDARD_BYTES 160u
#define DFY_STARTUP_RESOURCE_BYTES 32u
#define DFY_STARTUP_STANDARD_OFFSET 32u
#define DFY_STARTUP_RESOURCE_OFFSET 512u
#define DFY_STARTUP_ERROR_BYTES 16u
#define DFY_STARTUP_ENTRY_BYTES 16u
#define DFY_STARTUP_REFERENCE_ENTRY_BYTES 40u
#define DFY_STARTUP_CONTROL_ENV "DAFNYUTILS_STARTUP_FD"
#define DFY_STARTUP_FAILURE_EXIT 125

enum dfy_startup_control_offset {
  DFY_CONTROL_VERSION = 8, DFY_CONTROL_HEADER_BYTES = 12,
  DFY_CONTROL_TOTAL_BYTES = 16, DFY_CONTROL_RUNTIME_STDOUT = 20,
  DFY_CONTROL_RUNTIME_STDERR = 24, DFY_CONTROL_OBSERVER = 28,
  DFY_CONTROL_PRELOAD_PRESENT = 32, DFY_CONTROL_PRELOAD_LENGTH = 36,
  DFY_CONTROL_ORIGINAL_PRESENT = 40, DFY_CONTROL_ORIGINAL_LENGTH = 44,
  DFY_CONTROL_FLAGS = 48, DFY_CONTROL_RESERVED = 52, DFY_CONTROL_LAUNCH_ID = 56,
  DFY_CONTROL_EARLY_FD = 64, DFY_CONTROL_EARLY_RESERVED = 68
};

enum dfy_startup_source_state {
  DFY_SOURCE_CLOSED = 0, DFY_SOURCE_INHERITED = 1, DFY_SOURCE_EXEC_CLOSED = 2
};

#define DFY_STARTUP_MANAGED_TRANSFER 0
#define DFY_STARTUP_NATIVE_REFERENCE 1

enum dfy_startup_event_kind {
  DFY_EVENT_BOOTSTRAP_READY = 1, DFY_EVENT_BOOTSTRAP_ERROR = 2,
  DFY_EVENT_UTILITY_ENTERED = 3, DFY_EVENT_UTILITY_ENTRY_ERROR = 4
};

enum dfy_startup_phase {
  DFY_PHASE_CONTROL = 1, DFY_PHASE_CAPTURE = 2, DFY_PHASE_TRANSFER = 3,
  DFY_PHASE_ENVIRONMENT = 4, DFY_PHASE_UTILITY = 5,
  DFY_PHASE_LIBC_ENTRY = 6, DFY_PHASE_TRANSPORT = 7
};

enum dfy_startup_failure_kind {
  DFY_FAILURE_CONFIGURATION = 1, DFY_FAILURE_SYSTEM = 2
};

enum dfy_startup_configuration_error {
  DFY_CONFIG_MISSING_CONTROL = 1, DFY_CONFIG_INVALID_CONTROL_FD = 2,
  DFY_CONFIG_TRUNCATED = 3, DFY_CONFIG_MAGIC = 4, DFY_CONFIG_VERSION = 5,
  DFY_CONFIG_LENGTH = 6, DFY_CONFIG_FIELDS = 7, DFY_CONFIG_EXTRA_DATA = 8,
  DFY_CONFIG_LATE_INITIALIZATION = 9, DFY_CONFIG_LIFECYCLE = 10
};

/* API statuses and configuration codes must never be interpreted as errno. */
enum dfy_startup_api_status {
  DFY_STARTUP_OK = 0, DFY_STARTUP_NOT_BOOTSTRAPPED = 1,
  DFY_STARTUP_INVALID_ARGUMENT = 2, DFY_STARTUP_ALREADY_TAKEN = 3,
  DFY_STARTUP_ALREADY_ENTERED = 4, DFY_STARTUP_BUFFER_TOO_SMALL = 5,
  DFY_STARTUP_NATIVE_FAILURE = 6, DFY_STARTUP_TRANSPORT_FAILURE = 7,
  DFY_STARTUP_NOT_READY = 8, DFY_STARTUP_PROFILE_FORBIDS_TAKE = 9
};

#if defined(__GNUC__)
#define DFY_STARTUP_EXPORT __attribute__((visibility("default")))
#else
#define DFY_STARTUP_EXPORT
#endif

DFY_STARTUP_EXPORT int32_t dfy_startup_snapshot(
    uint8_t *bytes, uint32_t capacity, uint32_t *required_bytes);
DFY_STARTUP_EXPORT int32_t dfy_startup_take_standard(
    uint32_t role, int32_t *native_fd, uint32_t *availability_errno);
DFY_STARTUP_EXPORT int32_t dfy_startup_enter_utility(
    uint32_t *failure_kind, uint32_t *failure_code);

#endif
